name: debian-test-server

services:
  debian-server:
    privileged: true
    build:
      context: ..
      dockerfile: docker/Debian.SSH.Dockerfile
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - HISTFILE=/root/.bash_history
      - HISTSIZE=1000
      - HISTFILESIZE=2000
    ports:
      - "2222:22"
      - "8080:80"
      - "8043:443"
      - "12345:12345" # SSH alternative port after security hardening
    volumes:
      - ../logs:/var/log/app
      - ../logs/.bash_history:/root/.bash_history
      - docker-data:/var/lib/docker

# To resole a file system limitation issue with Docker in Docker
volumes:
  docker-data:
